### ISSUE TITLE
matrix_display_switch does not work with initial state = on

### ISSUE THREAD

**Issue by hn** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#5]
If you have a matrix_display_switch with initial state = on (due to `restore_mode` set or probably as well if the state is read from a saved state) the panel does not turn on:

```
switch:
  - platform: matrix_display_switch
    matrix_id: my_fancy_panel
    restore_mode: ALWAYS_ON
    id: matrix_power
```

If you then turn the switch on manually (or via lambda) later, the panel lights up again.
