### ISSUE TITLE
Unable to compile using ESP32-WROOM-32 on ESPHome latest version with Waveshare RGB-Matrix-P3-64x64

### ISSUE THREAD

**Issue by meteosat007** [TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper#8]
Hi followed the example yet I seem to get many i2s erors in the compile code attached.
<details closed>
<summary>Logs</summary>

```
INFO ESPHome 2023.8.2
INFO Reading configuration /config/esphome/terminal.yaml...
WARNING GPIO12 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO15 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing terminal (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- SPI @ 2.0.0
|-- Wire @ 2.0.0
|-- Adafruit BusIO @ 1.14.3
|-- Adafruit GFX Library @ 1.11.7
|-- ESP32 HUB75 LED MATRIX PANEL DMA Display @ 3.0.9+sha.54fb4a7
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
Compiling /data/terminal/.pioenvs/terminal/src/LED-Display-HUB75.cpp.o
Compiling /data/terminal/.pioenvs/terminal/src/esphome/components/esp32/preferences.cpp.o
Compiling /data/terminal/.pioenvs/terminal/src/esphome/components/font/font.cpp.o
Compiling /data/terminal/.pioenvs/terminal/src/esphome/components/logger/logger.cpp.o
Compiling /data/terminal/.pioenvs/terminal/src/esphome/components/matrix_display/matrix_display.cpp.o
Compiling /data/terminal/.pioenvs/terminal/src/esphome/components/matrix_display_brightness/matrix_display_brightness.cpp.o
Compiling /data/terminal/.pioenvs/terminal/src/esphome/components/matrix_display_switch/matrix_display_switch.cpp.o
In file included from src/esphome.h:25,
                 from src/LED-Display-HUB75.h:93,
                 from src/LED-Display-HUB75.cpp:2:
src/esphome/components/matrix_display/matrix_display.h:123:23: error: 'HUB75_I2S_CFG' has not been declared
       void set_driver(HUB75_I2S_CFG::shift_driver driver)
                       ^~~~~~~~~~~~~
src/esphome/components/matrix_display/matrix_display.h:123:51: error: expected ',' or '...' before 'driver'
       void set_driver(HUB75_I2S_CFG::shift_driver driver)
                                                   ^~~~~~
src/esphome/components/matrix_display/matrix_display.h:134:25: error: 'HUB75_I2S_CFG' has not been declared
       void set_i2sspeed(HUB75_I2S_CFG::clk_speed speed)
                         ^~~~~~~~~~~~~
src/esphome/components/matrix_display/matrix_display.h:134:50: error: expected ',' or '...' before 'speed'
       void set_i2sspeed(HUB75_I2S_CFG::clk_speed speed)
                                                  ^~~~~
src/esphome/components/matrix_display/matrix_display.h:211:7: error: 'MatrixPanel_I2S_DMA' does not name a type
       MatrixPanel_I2S_DMA *dma_display_ = nullptr;
       ^~~~~~~~~~~~~~~~~~~
src/esphome/components/matrix_display/matrix_display.h:214:7: error: 'HUB75_I2S_CFG' does not name a type
       HUB75_I2S_CFG::i2s_pins pins_;
       ^~~~~~~~~~~~~
src/esphome/components/matrix_display/matrix_display.h:220:7: error: 'HUB75_I2S_CFG' does not name a type
       HUB75_I2S_CFG::shift_driver driver_;
       ^~~~~~~~~~~~~
src/esphome/components/matrix_display/matrix_display.h:226:7: error: 'HUB75_I2S_CFG' does not name a type
       HUB75_I2S_CFG::clk_speed i2sspeed_;
       ^~~~~~~~~~~~~
src/esphome/components/matrix_display/matrix_display.h: In member function 'void esphome::matrix_display::MatrixDisplay::set_pins(esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*, esphome::InternalGPIOPin*)':
src/esphome/components/matrix_display/matrix_display.h:101:9: error: 'pins_' was not declared in this scope
         pins_ = {
         ^~~~~
src/esphome/components/matrix_display/matrix_display.h: In member function 'void esphome::matrix_display::MatrixDisplay::set_driver(int)':
src/esphome/components/matrix_display/matrix_display.h:126:9: error: 'driver_' was not declared in this scope
         driver_ = driver;
         ^~~~~~~
src/esphome/components/matrix_display/matrix_display.h:126:9: note: suggested alternative: 'writer_'
         driver_ = driver;
         ^~~~~~~
         writer_
src/esphome/components/matrix_display/matrix_display.h:126:19: error: 'driver' was not declared in this scope
         driver_ = driver;
                   ^~~~~~
src/esphome/components/matrix_display/matrix_display.h:126:19: note: suggested alternative: 'defer'
         driver_ = driver;
                   ^~~~~~
                   defer
src/esphome/components/matrix_display/matrix_display.h: In member function 'void esphome::matrix_display::MatrixDisplay::set_i2sspeed(int)':
src/esphome/components/matrix_display/matrix_display.h:137:9: error: 'i2sspeed_' was not declared in this scope
         i2sspeed_ = speed;
         ^~~~~~~~~
src/esphome/components/matrix_display/matrix_display.h:137:9: note: suggested alternative: 'i2s_read'
         i2sspeed_ = speed;
         ^~~~~~~~~
         i2s_read
src/esphome/components/matrix_display/matrix_display.h:137:21: error: 'speed' was not declared in this scope
         i2sspeed_ = speed;
                     ^~~~~
src/esphome/components/matrix_display/matrix_display.h:137:21: note: suggested alternative: 'send'
         i2sspeed_ = speed;
                     ^~~~~
                     send
In file included from src/LED-Display-HUB75.cpp:2:
src/LED-Display-HUB75.h: In member function 'void MatrixPanel_I2S_DMA::flipDMABuffer()':
src/LED-Display-HUB75.h:500:65: error: call of overloaded 'delay(int)' is ambiguous
         while(!i2s_parallel_is_previous_buffer_free()) { delay(1); }
                                                                 ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32@3.20005.220925/cores/esp32/Arduino.h:36,
                 from /data/cache/platformio/packages/framework-arduinoespressif32@3.20005.220925/libraries/WiFi/src/WiFiUdp.h:38,
                 from /data/cache/platformio/packages/framework-arduinoespressif32@3.20005.220925/libraries/DNSServer/src/DNSServer.h:3,
                 from src/esphome/components/captive_portal/captive_portal.h:5,
                 from src/esphome.h:16,
                 from src/LED-Display-HUB75.h:93,
                 from src/LED-Display-HUB75.cpp:2:
/data/cache/platformio/packages/framework-arduinoespressif32@3.20005.220925/cores/esp32/esp32-hal.h:132:6: note: candidate: 'void delay(uint32_t)'
 void delay(uint32_t);
      ^~~~~
In file included from src/esphome/core/application.h:7,
                 from src/esphome/components/api/api_connection.h:7,
                 from src/esphome.h:3,
                 from src/LED-Display-HUB75.h:93,
                 from src/LED-Display-HUB75.cpp:2:
src/esphome/core/hal.h:39:6: note: candidate: 'void esphome::delay(uint32_t)'
 void delay(uint32_t ms);
      ^~~~~
In file included from src/LED-Display-HUB75.cpp:2:
src/LED-Display-HUB75.h: In member function 'void MatrixPanel_I2S_DMA::showDMABuffer()':
src/LED-Display-HUB75.h:515:65: error: call of overloaded 'delay(int)' is ambiguous
         while(!i2s_parallel_is_previous_buffer_free()) { delay(1); }
                                                                 ^
In file included from /data/cache/platformio/packages/framework-arduinoespressif32@3.20005.220925/cores/esp32/Arduino.h:36,
                 from /data/cache/platformio/packages/framework-arduinoespressif32@3.20005.220925/libraries/WiFi/src/WiFiUdp.h:38,
                 from /data/cache/platformio/packages/framework-arduinoespressif32@3.20005.220925/libraries/DNSServer/src/DNSServer.h:3,
                 from src/esphome/components/captive_portal/captive_portal.h:5,
                 from src/esphome.h:16,
                 from src/LED-Display-HUB75.h:93,
                 from src/LED-Display-HUB75.cpp:2:
/data/cache/platformio/packages/framework-arduinoespressif32@3.20005.220925/cores/esp32/esp32-hal.h:132:6: note: candidate: 'void delay(uint32_t)'
 void delay(uint32_t);
      ^~~~~
In file included from src/esphome/core/application.h:7,
                 from src/esphome/components/api/api_connection.h:7,
                 from src/esphome.h:3,
                 from src/LED-Display-HUB75.h:93,
                 from src/LED-Display-HUB75.cpp:2:
src/esphome/core/hal.h:39:6: note: candidate: 'void esphome::delay(uint32_t)'
 void delay(uint32_t ms);
      ^~~~~
*** [/data/terminal/.pioenvs/terminal/src/LED-Display-HUB75.cpp.o] Error 1
========================= [FAILED] Took 16.31 seconds =========================
```
</details>

My yaml is below.
```
esphome:
  name: "terminal"
  friendly_name: Terminal
  platformio_options:
    lib_deps:
      - SPI
      - Wire
      - Adafruit BusIO
      - adafruit/Adafruit GFX Library
      - https://github.com/TillFleisch/ESP32-HUB75-MatrixPanel-DMA#optional_logging

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<redacted>"

ota:

time:
  - platform: sntp
    id: ntp
    timezone: Europe/London
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "<redacted>"
    password: <redacted>"

captive_portal:

font:
  - file: "fonts/Google-Sans-Medium.ttf"
    id: small_font
    size: 25
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '(', ')', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', 'å', 'ä', 'ö', '/']


display:
  - platform: matrix_display
    id: matrix
    width: 64
    height: 64
    R2_pin: 14
    G2_pin: 12
    B2_pin: 13
    E_pin: 32

    lambda: |-
      it.print(0, 0, id(small_font), "Hello World!");

switch:
  - platform: matrix_display_switch
    matrix_id: matrix
    name: "Power"
    id: power

number:
  - platform: matrix_display_brightness
    matrix_id: matrix
    name: "Brightness"
```

Look forward to what is probably a simple fix in my lack of understanding here.

Alan
